server:
  port:8081

spring:
  datasource:
    name: mssqlDB
    url: jdbc:mysql://81.68.104.162:3306/wms?allowPublicKeyRetrieval=true&serverTimeZone=GMT
    username: root
    password: xaXu4q8h<t5
  thymeleaf:
    prefix: classpath:/templates/
    #开发，不需要重启
    cache: false
    suffix: .html
    mode: HTML
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.apolo.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

